spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: ${DATASOURCE.URL}
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8080



