spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false

#  datasource:
#    url: ${DATASOURCE.URL}
#    username: ${DATASOURCE.USERNAME}
#    password: ${DATASOURCE.PASSWORD}


  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:bank}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123123}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8080