spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/online_toy_store
    username: root
    password: 23402

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml




